# Day 3: Crossed Wires

## Part 1

The gravity assist was successful, and you're well on your way to the Venus refuelling station. During the rush back on Earth, the fuel management system wasn't completely installed, so that's next on the priority list.

Opening the front panel reveals a jumble of wires. Specifically, two wires are connected to a central port and extend outward on a grid. You trace the path each wire takes as it leaves the central port, one wire per line of text (your puzzle input).

The wires twist and turn, but the two wires occasionally cross paths. To fix the circuit, you need to find the intersection point closest to the central port. Because the wires are on a grid, use the Manhattan distance for this measurement. While the wires do technically cross right at the central port where they both start, this point does not count, nor does a wire count as crossing with itself.

For example, if the first wire's path is R8,U5,L5,D3, then starting from the central port (o), it goes right 8, up 5, left 5, and finally down 3:

...........

...........

...........

....+----+.

....|....|.

....|....|.

....|....|.

.........|.

.o-------+.

...........

Then, if the second wire's path is U7,R6,D4,L4, it goes up 7, right 6, down 4, and left 4:

...........

.+-----+...

.|.....|...

.|..+--X-+.

.|..|..|.|.

.|.-X--+.|.

.|..|....|.

.|.......|.

.o-------+.

...........

These wires cross at two locations (marked X), but the lower-left one is closer to the central port: its distance is 3 + 3 = 6.

Here are a few more examples:

- R75,D30,R83,U83,L12,D49,R71,U7,L72,U62,R66,U55,R34,D71,R55,D58,R83 = distance 159
- R98,U47,R26,D63,R33,U87,L62,D20,R33,U53,R51, U98,R91,D20,R16,D67,R40,U7,R15,U6,R7 = distance 135

What is the Manhattan distance from the central port to the closest intersection?

In [230]:
# data wrangling
import pandas as pd
import numpy as np

### Blank grid function

In [231]:
def init_grid():
    grid = np.zeros((10,11))
    grid[-2,1] = 1
    return grid

### Test example small

#### Initialize grid and draw wire 1

In [226]:
grid = init_grid()
wire = "R8,U5,L5,D3".split(",")
path = [-2,1]

In [227]:
# loop through each direction
for step in range(len(wire)):
    y = path[0] #define starting locations
    x = path[1]
    movement = int(wire[step][1]) #set total movement
    
    if wire[step][0] == "R": 
        path[1] += movement
        for move in range(movement):
            grid[y,x+move+1] = 1

    elif wire[step][0] == "L":
        path[1] -= movement
        for move in range(movement):
            grid[y,x-move-1] = 1

    elif wire[step][0] == "D":
        path[0] += movement
        for move in range(movement):
            grid[y+move+1,x] = 1
        
    elif wire[step][0] == "U":        
        path[0] -= movement
        for move in range(movement):
            grid[y-move-1,x] = 1

    else:
        print("error")
print(grid)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### Draw wire 2

In [228]:
wire = "U7,R6,D4,L4".split(",")
path = [-2,1]

In [229]:
for step in range(len(wire)):
    y = path[0]
    x = path[1]
    movement = int(wire[step][1])
    
    if wire[step][0] == "R":
        path[1] += movement
        for move in range(movement):
            if grid[y,x+move+1] == 1:
                grid[y,x+move+1] = 3
            else:
                grid[y,x+move+1] = 2                

    elif wire[step][0] == "L":
        path[1] -= movement
        for move in range(movement):
            if grid[y,x-move-1] == 1:
                grid[y,x-move-1] = 3
            else:
                grid[y,x-move-1] = 2

    elif wire[step][0] == "D":
        path[0] += movement
        for move in range(movement):
            if grid[y+move+1,x] == 1:
                grid[y+move+1,x] = 3
            else:
                grid[y+move+1,x] = 2
        
    elif wire[step][0] == "U":        
        path[0] -= movement
        for move in range(movement):
            if grid[y-move-1,x] == 1:
                grid[y-move-1,x] = 3
            else:
                grid[y-move-1,x] = 2

    else:
        print("error")
print(grid)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 2. 2. 2. 2. 2. 2. 2. 0. 0. 0.]
 [0. 2. 0. 0. 0. 0. 0. 2. 0. 0. 0.]
 [0. 2. 0. 0. 1. 1. 1. 3. 1. 1. 0.]
 [0. 2. 0. 0. 1. 0. 0. 2. 0. 1. 0.]
 [0. 2. 0. 2. 3. 2. 2. 2. 0. 1. 0.]
 [0. 2. 0. 0. 1. 0. 0. 0. 0. 1. 0.]
 [0. 2. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


The '3' values are where wires intersect

#### Find shortest distance

In [242]:
intersect = np.where(grid == 3)
intersect = list(zip(intersect[0], intersect[1]))
intersect

[(3, 7), (5, 4)]

In [257]:
start = [8,1]

In [273]:
short_dist = None

for count in range(len(intersect)):
    dist = abs(intersect[count][0] - start[0]) + abs(intersect[count][1] - start[1])
    if short_dist is None:
        short_dist = dist
    elif dist < short_dist:
        short_dist = dist
        short_index = count

In [277]:
short_dist

6

In [276]:
intersect[short_index]

(5, 4)

### Test big examples

In [280]:
wire = "R75,D30,R83,U83,L12,D49,R71,U7,L72,U62,R66,U55,R34,D71,R55,D58,R83".split(",")

Determine grid size 

In [294]:
wire = "U7,R6,D4,L4".split(",")

In [297]:
width = 1
height = 1

for step in range(len(wire)):
    if wire[step][0] == "R":
        width += int(wire[step][1:])
    elif wire[step][0] == "U":
        height += int(wire[step][1:])
        
width, height

(7, 8)

In [299]:
wire = "R8,U5,L5,D3".split(",")

In [300]:
width = 1
height = 1

for step in range(len(wire)):
    if wire[step][0] == "R":
        width += int(wire[step][1:])
    elif wire[step][0] == "U":
        height += int(wire[step][1:]) 
        
width, height

(9, 6)

> need to compare widths and heights and use the max sizes of both 